### ISSUE TITLE
[bug] in USA theme

### ISSUE THREAD

**Issue by trains58554** [osclass/osclass-themes#18]
The USA map goes over the first listing making it impossible to click on the first listing. What I did to fix the problem was set the z-index to -1 and then the map goes behind the first listing and you can again click on the first listing.

Jay

**Comment by juanramon** [comment]
Perhaps it will be better if we add a margin-bottom or something like this? Or I'm missing something?

**Comment by trains58554** [comment]
I just looked at the USA theme and the z-index was not quite the right change.

I think just adjusting the hight down to 460 instead of 562 will be all that is needed as then the image does not go over the first latest listing.

position:absolute;left:0; top:2px; width:707px; height:460px; 

Jay

**Comment by ghost** [comment]
This will fix the bug in the USA Theme.   Edit the main.php file.

find the line:
<img src="<?php echo osc_current_web_theme_url('images/map.png'); ?>" alt="usa" usemap="#Map" border="0" style="position:absolute;left:0; top:2px; width:707px; height:562px; opacity:0" width="707" height="562"/>

and change to:
<img src="<?php echo osc_current_web_theme_url('images/map.png'); ?>" alt="usa" usemap="#Map" border="0" style="position:absolute;left:0; top:2px; width:695px; height:445px; opacity:0" width="695" height="445"/>

**Comment by conejoninja** [comment]
moved here : https://github.com/osclass/theme-maps/issues/1
