### ISSUE TITLE
Bug in Real Estate Theme Zip file

### ISSUE THREAD

**Issue by Andresvendedor** [osclass/osclass-themes#19]
I just tried to download the latest zip file 1.0.6 for the Real Estate Theme, and I get an error message that the file is invalid (unexpected end of archive) Tried to open it with windows and with winrare - same problem with both programs.

Andresvendedor

**Comment by feralou** [comment]
We had problems with Sourceforge lately, so we migrated our files to our own server, Sourceforge is only a mirror. I updated the file, and I uploaded to Sourceforge the latest version 1.0.7.

I hope you doesn't have problems with latest zips, also, I recommend download the files from the Osclass Market http://market.osclass.org
