### ISSUE TITLE
[bug] In Modern Theme (Default Theme)

### ISSUE THREAD

**Issue by john-ray** [osclass/osclass-themes#21]
What were you trying to do?
I was testing the mobile page by creating a new ad posting with PayPal as payment method.

What did you click on or do last?
On clicking the "publish" button on the ad posting page after filling all required field.

What happened / what did you see?

Fatal error: Cannot redeclare theme_modern_actions_admin() (previously declared in C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\osclass\oc-content\themes\modern\functions.php:38) in C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\osclass\oc-includes\osclass\gui\functions.php on line 79

What browser are you using?
Opera mini as the mobile phone browser.

What version of OSClass?
OSClass 3.0.2

What hosting provider? (And if you know, what version of PHP do they use?) 
Local Hosting on my home server with PHP version 5.2.8

**Comment by texhiller** [comment]
Same problem. osc mobile version 0.3. The cause is: payment plugin conflict.
