### ISSUE TITLE
Probable invalid request.

### ISSUE THREAD

**Issue by jayvi** [osclass/osclass-themes#25]
Probable invalid request.

When i try to activate a theme no matter whitch one.

Help please

**Comment by conejoninja** [comment]
Hi tamqncho,

Are you using the develop branch? I will fix it as soon as possible (maybe tomorrow)

I moved the issue here : https://github.com/osclass/Osclass/issues/603

**Comment by jayvi** [comment]
dont worry i am developer and fix it :D but its good to know that also you have a problem with uploading listing from normal user - cant upload listing. I fix that to you have a If(){} in one of the files but i cant remember which one was it because i make a lot of corections and now its work really great :)
