### ISSUE TITLE
[Bender] User account - menu fixes - Account 

### ISSUE THREAD

**Issue by garciademarina** [osclass/osclass-themes#34]
Move links  **'Change email' / 'Change username' / 'Change password' / 'Delete account'** inside 'My account' page, as modern theme. 

This links don't have to be so accesible.

**Comment by garciademarina** [comment]
All link elements to **'Change email' / 'Change username' / 'Change password' / 'Delete account'** should have a unique **id** for testing purpose.

id="change_email_link"

id="change_usename_link"

id="change_password_link"

id="delete_account_link"

**Comment by feralou** [comment]
Fixed on develop commit https://github.com/osclass/osclass/commit/9c7a240e9cae621229aac5d79b7b6e802edc2277
