### ISSUE TITLE
[admin area] widget area empty

### ISSUE THREAD

**Issue by JoeNewYork** [osclass/osclass-themes#55]
widget area in admin is empty in new install of osclass 3.3.2
![h01u3](https://f.cloud.github.com/assets/6232152/1803891/d3d344a8-6c2e-11e3-99f0-7d6563b2dfce.jpg)

**Comment by conejoninja** [comment]
Can not reproduce the problem. Widgets depends on the theme, which version of bender are you using ?

**Comment by JoeNewYork** [comment]
Brand new installation of 3.3.2 with default bender theme
