### ISSUE TITLE
[bender - admin area] Theme settings dont save

### ISSUE THREAD

**Issue by JoeNewYork** [osclass/osclass-themes#56]
When saving theme settings, it doesnt get updated.

theme settings are not saved, 
fig 1. 

I changed the search place holder , unchecked the check box

![jtbdx](https://f.cloud.github.com/assets/6232152/1803899/4b8965cc-6c2f-11e3-9e41-1c2d189888d9.jpg)

fig 2.

result

![afzzp](https://f.cloud.github.com/assets/6232152/1803900/6982ac64-6c2f-11e3-809e-6972cf600b07.jpg)

**Comment by conejoninja** [comment]
Hi,

Which version of bender are you using ?

Latest one should have an extra option for configuration : http://i.imgur.com/eFWAK18.png

Also, the correct place to post this issue should be here : https://github.com/osclass/theme-bender

**Comment by JoeNewYork** [comment]
I use brand new installation of osclass 3.3.2 with default bender theme.
I know, it should have had additional option, in fact it had that option
for a day, but it disappeard, which is very strange, and a bug onto itself.
If you wish i can give acces to my server to check it out yourself.
I have two installations with same problem, so its not just one corupted
installation.

**Comment by JoeNewYork** [comment]
I now see same bug was already reported by yourself.
https://github.com/osclass/osclass-themes/issues/44
