### ISSUE TITLE
[bender] grid view text overflow 

### ISSUE THREAD

**Issue by JoeNewYork** [osclass/osclass-themes#57]
here is another bug, that can get fixed with a simple css "clear" attribute, but its still there in the latest version.

http://forums.osclass.org/bender/bender-grid-view-help/

Problem was reported september, but here you can see the bug in action in the latest version!

http://demo.osclass.org/general/?theme=bender (select gallery view)

**Comment by conejoninja** [comment]
Hi,

Thanks for the report, I moved the issue to the correct place, the specific bender repository : https://github.com/osclass/theme-bender/issues/5
