### ISSUE TITLE
Correct handling of "magic" quotes

### ISSUE THREAD

**Issue by schopenhauer** [osclass/osclass-themes#6]
There is an incorrect handling of quotes in the theme, depending on the site language.
Here is a simple example on the page "index.php?page=search".

in English:
There are no results matching "test"

in French:
Il n'y a aucun résultat correspondant à \"test\"

I am not sure, if this appears on other places on the theme.

**Comment by feralou** [comment]
@schopenhauer thanks for reporting this bug!

Can you specify about what theme or themes you are talking about?

**Comment by schopenhauer** [comment]
I observed this on the "Real estate" theme, but thought it was a more general problem.
